# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wattApp', '0004_auto_20171109_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
