# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wattApp', '0009_auto_20171109_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('humidityGoal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TMesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wattApp.Plant')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wattApp.User'),
        ),
        migrations.AddField(
            model_name='hmesure',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wattApp.Plant'),
        ),
    ]
