# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wattApp', '0011_auto_20171110_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmeasure',
            name='plant',
        ),
        migrations.AddField(
            model_name='tmeasure',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wattApp.User'),
            preserve_default=False,
        ),
    ]
